name: effective-model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
        - mlflow-skinny==2.18
        - h5py==3.12.1
        - statsmodels==0.14.4
        - pyscf==2.7.0
        - pandas==2.2.3
        - rich==13.9.4
        - matplotlib==3.9.3
        - seaborn==0.13.2
